language: go

go:
- 1.1
- 1.2
- 1.3

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install snmpd
 - sudo service snmpd start

install:
- go get github.com/soniah/gosnmp

script:
- ./non-verax-tests.sh
